name: Update FIFA Playlist

on:
  schedule:
    - cron: '*/30 * * * *' # Auto-run setiap 30 menit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python fifa_grabber.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add f.m3u
          git commit -m "Update f.m3u: $(date)" || exit 0
          git push
