name: Generate Mod Playlist & Logos

on:
  schedule:
    - cron: '0 * * * *' # Berjalan otomatis setiap 6 jam
  workflow_dispatch:      # Bisa diklik manual dari tab Actions

jobs:
  process-logos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow "rembg[cpu]"

      - name: Run Logo Processor
        run: python process_m3u.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          # Tambahkan semua perubahan, termasuk file M3U yang namanya baru
          git add logos/ *.m3u
          git commit -m "Auto-generate modified playlist and logos [skip ci]" || echo "No changes to commit"
          git push
